apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cpu-tanzu-java-web-app
  labels:
    app.kubernetes.io/part-of: cpu-tanzu-java-web-app
    apps.tanzu.vmware.com/language: java
    apps.tanzu.vmware.com/supplychain: cpu-test-scan
    apps.tanzu.vmware.com/workload-type: cpu-web
    app.kubernetes.io/component: run
    carto.run/workload-name: cpu-tanzu-java-web-app
spec:
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.7.3
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"cpu-tanzu-java-web-app","apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/supplychain":"cpu-test-scan","apps.tanzu.vmware.com/workload-type":"cpu-web"},"name":"cpu-tanzu-java-web-app","namespace":"developer"},"spec":{"params":[{"name":"git_user_email","value":"cpulcini2003@gmail.com"},{"name":"git_user_name","value":"cpulcini2003"},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"cpulcini2003"},{"name":"gitops_repository_name","value":"cpu-acic1"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/sample-accelerators/tanzu-java-web-app"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: cpu-tanzu-java-web-app
        apps.tanzu.vmware.com/language: java
        apps.tanzu.vmware.com/supplychain: cpu-test-scan
        apps.tanzu.vmware.com/workload-type: cpu-web
        carto.run/workload-name: cpu-tanzu-java-web-app
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: cpu-tanzu-java-web-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.h2o-4-933.h2o.vmware.com/tap-project/supply-chain2/cpu-tanzu-java-web-app-developer@sha256:86e2873768f89ee7fdff02ea62565eb2b4bbaa68186ee173293be78b3e061fc6
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

